version: '3.3'

services:
  postgres:
    image: postgres:17.2
    hostname: postgres
    user: postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: randompassword
    command: postgres -c 'max_connections=450'
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 10s
    deploy:
      resources:
        limits:
          cpus: '0.4'
          memory: '1.5GB'

  redis:
    image: redis:7.4.2
    hostname: redis
    command: redis-server --save "" --appendonly no --maxclients 20000
    ports:
      - "6379:6379"
    deploy:
      resources:
        limits:
          cpus: '0.15'
          memory: '0.3GB'


networks:
  default:
    driver: bridge
    name: medium
