version: '3.3'

services:
  postgres:
    image: postgres:17.2
    user: postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: randompassword
    command: postgres -c 'max_connections=450'
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 10s
    deploy:
      resources:
        limits:
          cpus: '0.4'
          memory: '1.5GB'

networks:
  default:
    driver: bridge
    name: medium
